config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :my do
    resources :bands, only:[:index]
  end

  resources :bands, only: [:show, :create] do
    resources :tracks, only:[:create]
  end

  resources :tracks, only:[:index, :show] do
    resources :comments, only:[:create]
    resources :partitions, only:[:create, :show, :destroy, :update]
    resources :recordings, only:[:index, :create, :destroy, :update]
    resources :inspirations, only:[:create, :update, :destroy]
  end

  resources :partitions, only: [:show]
  resources :inspirations, only: [:show]

end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :user
  belongs_to :partition
  has_one :instrument, through: :partition

  validates :name, presence: true

  has_one_attached :resource
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  def index
    @track = Track.find(params[:track_id])
  end

  def create
    @recording = Recording.new(recording_params)
    @recording.user = current_user
    @track = Track.find(params[:track_id])

    @partition = Partition.new
    @inspiration = Inspiration.new

    if @recording.save
      redirect_to track_path(@track)
    else
      @comment = Comment.new
      render 'tracks/show'
    end
  end

  def update
    @recording = Recording.find(params[:id])
    @recording.update(recording_params)
    redirect_to track_path(params[:track_id])
  end

  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy
    redirect_to track_path(params[:track_id])
  end

  private

  def recording_params
    params.require(:recording).permit(:name, :partition_id, :resource, :is_lead)
  end
end

app/views/recordings/_index-show.html.erb
<% @track.recordings.each do |recording| %>
  <div class="d-flex card-recording shadow-orange">
    <div class="d-flex align-items-center m-auto" style= "width: 50%">
      <input type="checkbox" class="toggle check-recordings" data-recordurl="<%= cloudinary_url(recording.resource.key, resource_type: :video) %>" id=<%= "select-recording-#{recording.id}" %> >
      </input>
      <label class="mb-0" for=<%= "select-recording-#{recording.id}" %> >
        <%= recording.name %>

        <span class="text-highlight text-badge ml-3">
          <span>
            recorded by <%= recording.user.first_name %>
          </span>
        </span>
      </label>

    </div>
    <div class="instrument mr-2">
        <% case recording.instrument.name %>
          <% when "Guitar" %>
            <%= image_tag "icon_acoustic_guitar.svg", class: "resource-card-icon" %>
          <% when "Bass" %>
            <%= image_tag "icon_electric_bass.svg", class: "resource-card-icon" %>
          <% when "Drums" %>
            <%= image_tag "icon_drums.svg", class: "resource-card-icon" %>
          <% when "Vocals" %>
            <%= image_tag "icon_microphone.svg", class: "resource-card-icon" %>
          <% else %>
            <%= image_tag "icon_music.svg", class: "resource-card-icon" %>
          <% end %>
      </div>
    <div class="m-auto" style="width: 40%">
      <audio src="<%= cloudinary_url(recording.resource.key, resource_type: :video)  %>" controls></audio>
    </div>
  </div>
<% end %>

app/views/recordings/_index.html.erb
<div class="container rounded py-3">
  <div class="d-flex align-items-center">
    <h3 class="title-32 text-shadow-orange">Recordings</h3>

    <%= link_to "#recordingModal", class: "btn btn-plus ml-3", "data-toggle" => "modal" do %>
      <h3><i class="fas fa-plus-circle"></i></h3>
    <% end %>
  </div>

  <% @track.recordings.each do |recording| %>
    <div class="resource-card grow-resource">
      <%= link_to "#musicPlayer-#{recording.id}", class: "track-show-play", 'data-toggle' => 'collapse', 'data-target' => "#audio-player-#{recording.id}" do %>
        <div class="d-flex align-items-center">

          <% case recording.instrument.name %>
          <% when "Guitar" %>
            <%= image_tag "icon_acoustic_guitar.svg", class: "resource-card-icon" %>
          <% when "Bass" %>
            <%= image_tag "icon_electric_bass.svg", class: "resource-card-icon" %>
          <% when "Drums" %>
            <%= image_tag "icon_drums.svg", class: "resource-card-icon" %>
          <% when "Vocals" %>
            <%= image_tag "icon_microphone.svg", class: "resource-card-icon" %>
          <% else %>
            <%= image_tag "icon_music.svg", class: "resource-card-icon" %>
          <% end %>


          <p>
            <%= recording.name %>
          </p>
        </div>
      <% end %>
      <div class="d-flex ml-auto align-items-center">
        <div class="icon-display-hover">
          <%= link_to "#recordingModalUpdate-#{recording.id}", "data-toggle" => "modal" do %>
          <i class="fas fa-pencil-alt mr-2"></i>
          <% end %>
          <%= link_to track_recording_path(@track, recording), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="far fa-trash-alt mr-3"></i>
          <% end %>
        </div>
        <% if recording.is_lead %>
          <i class="fas fa-star text-orange resource-star mr-3"></i>
        <% end %>
        <%= link_to "#musicPlayer-#{recording.id}", class: "track-show-play", 'data-toggle' => 'collapse', 'data-target' => "#audio-player-#{recording.id}" do %>
          <i class="far fa-play-circle btn-plus resource-play ml-auto mr-1"></i>
        <% end %>
      </div>
    </div>

    <div id="audio-player-<%= recording.id %>" class="collapse">
      <audio src="<%= cloudinary_url(recording.resource.key, resource_type: :video)  %>" controls></audio>
    </div>
  <% end %>
</div>

app/views/recordings/index.html.erb
<div class="banner-small">
  <div class="banner-slanted"></div>
  <%#= image_tag "rocks.png", alt: "Rock on hand sign" ,id: "rocks" %>

  <h1>Let's mix it !</h1>
  <h3><%= @track.title %></h3>
  <div class="align-items-center">
    <%= render "shared/button_back_to_track"%>
  </div>
</div>

<div class="container" style="margin-top:140px">

<div id="particles-js"></div>
<div class="container">

  <%= render 'recordings/index-show' %>

  <div class="text-center mt-5">
    <div class="btn btn-blue play-recordings">
      <i class="fas fa-sliders-h"></i> Play Mix
    </div>
<!--     <div class="btn btn-blue pause-recordings ">
      <i class="fas fa-pause"></i> Pause
    </div> -->
    <div class="btn btn-blue stop-recordings button-inactive">
      <i class="fas fa-stop"></i> Stop
    </div>
    <div class="btn btn-blue download-mix">
      <i class="fas fa-download"></i> Download Mix
    </div>
  </div>
</div>