config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :my do
    resources :bands, only:[:index]
  end

  resources :bands, only: [:show, :create] do
    resources :tracks, only:[:create]
  end

  resources :tracks, only:[:index, :show] do
    resources :comments, only:[:create]
    resources :partitions, only:[:create, :show, :destroy, :update]
    resources :recordings, only:[:index, :create, :destroy, :update]
    resources :inspirations, only:[:create, :update, :destroy]
  end

  resources :partitions, only: [:show]
  resources :inspirations, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :tracks

  has_one_attached :photo

  validates :name, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :track
  belongs_to :user

  validates :content, presence: true
end

app/models/inspiration.rb
class Inspiration < ApplicationRecord
  belongs_to :track
  belongs_to :user

  validates :name, presence: true

  has_one_attached :resource
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :users
  has_many :partitions
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :band
end

app/models/partition.rb
class Partition < ApplicationRecord
  belongs_to :user
  belongs_to :track
  has_many :recordings
  belongs_to :instrument

  has_one_attached :resource

  validates :name, presence: true
  validates :instrument, presence: true
end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :user
  belongs_to :partition
  has_one :instrument, through: :partition

  validates :name, presence: true

  has_one_attached :resource
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :band
  has_many :comments
  has_many :inspirations
  has_many :partitions
  has_many :recordings, through: :partitions
  has_one_attached :photo

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :members
  has_many :inspirations
  has_many :partitions
  has_many :recordings
  has_many :comments
  has_many :bands, through: :members
  belongs_to :instrument

  has_one_attached :avatar

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :avatar, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def set_locale
    # if user_signed_in?
    #   I18n.locale = current_user.language
    # else
    # end
    I18n.locale = params[:locale] || locale_from_header || I18n.default_locale
  end

  def locale_from_header
    request.env.fetch('HTTP_ACCEPT_LANGUAGE', '').scan(/[a-z]{2}/).first
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :instrument_id, :avatar])
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def show
    @band = Band.find(params[:id])
    @track = Track.new
    @member = Member.new
  end

  def create
    @band = Band.new(band_params)
    @band.creation_year = Date.today.year unless @band.creation_year != ""
    member = Member.new(user: current_user, band: @band)

    if @band.save && member.save
      redirect_to band_path(@band)
    else
      @band = Band.new
      render 'my/bands/index'
    end
  end

  private

  def band_params
    params.require(:band).permit(:name, :description, :creation_year, :photo)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # skip_before_action :verify_authenticity_token

  def create
    @track = Track.find(params[:track_id])
    @comment = Comment.new(comment_params)
    @comment.track = @track
    @comment.user = current_user
    if @comment.save
      TrackChannel.broadcast_to(
        @track,
        render_to_string(partial: "comment", locals: { comment: @comment })
      )
      redirect_to track_path(@track, anchor: "comment-#{@comment.id}")
    else
      render 'tracks/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :test ]

  def home
  end

end

app/controllers/partitions_controller.rb
class PartitionsController < ApplicationController
  def show
    @partition = Partition.find(params[:id])
    @recording = Recording.all
    @new_recording = Recording.new
    @track = @partition.track
  end

  def create
    @partition = Partition.new(partition_params)
    @partition.user = current_user
    @track = Track.find(params[:track_id])
    @partition.track = @track

    @recording = Recording.new
    @inspiration = Inspiration.new

    if @partition.save
      redirect_to track_path(@track)
    else
      @comment = Comment.new
      render 'tracks/show'
    end
  end

  def update
    @partition = Partition.find(params[:id])
    @partition.update(partition_params)
    redirect_to track_path(params[:track_id])
  end

  def destroy
    @partition = Partition.find(params[:id])
    @partition.destroy
    redirect_to track_path(params[:track_id])
  end

  private

  def partition_params
    params.require(:partition).permit(:name, :instrument_id, :resource)
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  def index
    @track = Track.find(params[:track_id])
  end

  def create
    @recording = Recording.new(recording_params)
    @recording.user = current_user
    @track = Track.find(params[:track_id])

    @partition = Partition.new
    @inspiration = Inspiration.new

    if @recording.save
      redirect_to track_path(@track)
    else
      @comment = Comment.new
      render 'tracks/show'
    end
  end

  def update
    @recording = Recording.find(params[:id])
    @recording.update(recording_params)
    redirect_to track_path(params[:track_id])
  end

  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy
    redirect_to track_path(params[:track_id])
  end

  private

  def recording_params
    params.require(:recording).permit(:name, :partition_id, :resource, :is_lead)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
  end

  def show
    @track = Track.find(params[:id])
    @comment = Comment.new
    @recording = Recording.new
    @partition = Partition.new
    @inspiration = Inspiration.new
  end

  def create
    @track = Track.new(track_params)

    @band = Band.find(params[:band_id])
    @track.band = @band

    # default values
    @track.duration = 180 unless @track.duration
    @track.tempo = 120 unless @track.tempo

    if @track.save
      redirect_to track_path(@track)
    else
      render 'bands/show'
    end
  end

  private

  def track_params
    params.require(:track).permit(:title, :artist, :style, :duration, :tempo, :pattern, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag asset_path('microphone.png') %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

     <%= yield %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<div id="particles-js"></div>
<div class="banner-home-page d-flex flex-column">
  <div class="container-home-page d-flex flex-column">
    <div class="row">
      <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
        <h1><%= t('never_alone') %></h1>
        <p><%= t('.explanation') %></p>
        <%= link_to t('.play_now'), my_bands_path, class: "bubbly-button" %>
      </div>
      <div class="col-lg-6 col-sm-6 col-md -6text-center">
        <div><%= cl_image_tag("voice_m0cqki", width: 300, height: 200, crop: :fill, class: "photo-banner") %></div>
        <div class="guitar"><%= cl_image_tag("guitar_gmvcmd", width: 300, height: 200, crop: :fill, class: "photo-banner") %></div>
      </div>
    </div>
    <div class="text-scroll"><h3 class="text-center"><%= t('.how_it_works') %></h3></div>
    <div class="d-flex justify-content-center">
      <div class="container-scroll">
        <div class="chevron"></div>
        <div class="chevron"></div>
        <div class="chevron"></div>
      </div>
    </div>
  </div>
</div>


<div class="container-home-page">
  <div class="row section-feature d-flex justify-content-center align-items-center">
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <div><%= cl_image_tag("crew_zjp48v", width: 400, class: "photo-banner") %></div>
    </div>
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <h2 class="text-shadow-orange title-feature"><%= t('.create_team') %></h2>
      <p><%= t('.create_team_expl') %></p>
    </div>
  </div>
  <div class="row section-feature d-flex justify-content-center align-items-center">
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <h2 class="text-shadow-orange title-feature"><%= t('.choose_tracks') %></h2>
      <p><%= t('.choose_tracks_expl') %></p>
    </div>
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <div><%= cl_image_tag("tracks_vivusr", width: 400, class: "photo-banner") %></div>
    </div>
  </div>
  <div class="row section-feature d-flex justify-content-center align-items-center">
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <div><%= cl_image_tag("tabs_tgtr2a", width: 400, class: "photo-banner") %></div>
    </div>
    <div class="col-lg-5 col-sm-6 col-md-6 mt-5">
      <h2 class="text-shadow-orange title-feature"><%= t('.import_sheets') %></h2>
      <p><%= t('.import_sheets_expl') %></p>
    </div>
  </div>
  <div class="row section-feature d-flex justify-content-center align-items-center">
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <h2 class="text-shadow-orange title-feature"><%= t('.record') %></h2>
      <p><%= t('.record_expl') %></p>
    </div>
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <div><%= cl_image_tag("record_n6dt4r", width: 400, class: "photo-banner") %></div>
    </div>
  </div>
  <div class="row section-feature d-flex justify-content-center align-items-center">
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <div><%= cl_image_tag("mix_g9uufn", width: 400, class: "photo-banner") %></div>
    </div>
    <div class="col-lg-6 col-sm-6 col-md-6 mt-5">
      <h2 class="text-shadow-orange title-feature"><%= t('.mix_share') %></h2>
      <p><%= t('.mix_share_expl') %></p>
    </div>
  </div>
</div>

<div style="position:relative; height:400px">
  <div class="banner-testimonial-home-page">
    <%= image_tag "rocks-inverse.png", alt: "Rock on hand sign" ,id: "rockshome" %>
    <p class="text-center testimonial"><%= t('.feedback_1') %></p>
    <div class="d-flex justify-content-center"><%= image_tag "emilie.jpg", alt: "emilie", id: "avatar-testimonial" %></div>
    <p class="text-center">Emilie</p>
  </div>
</div>

app/views/shared/_button_back.html.erb
<%= link_to  :back, class: "btn btn-back" do %>
  <i class="fas fa-fast-backward"></i>
<% end %>

app/views/shared/_button_back_to_band.html.erb
<%= link_to band_path(@track.band_id), class: "btn btn-back" do %>
  <i class="fas fa-fast-backward"></i>
<% end %>

app/views/shared/_button_back_to_my_bands.html.erb
<%= link_to my_bands_path, class: "btn btn-back" do %>
  <i class="fas fa-fast-backward"></i>
<% end %>

app/views/shared/_button_back_to_track.html.erb
<%= link_to  track_path(@track), class: "btn btn-back" do %>
  <i class="fas fa-fast-backward"></i>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
    <div class="container">
     <span>(<i class="fas fa-microphone-alt"></i>) <%= t('never_alone') %> !</span>
    </div>
</footer>

app/views/shared/_modal_add_inspiration.html.erb
<div class="modal fade" id="inspirationModal" tabindex="-1" role="dialog" aria-labelledby="partitionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h6 class="modal-title">Add a new source of inspiration</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for [@track, @inspiration] do |f| %>
          <%= f.input :name %>
          <%= f.input :resource, as: :file %>

          <div class="text-center mt-4">
            <%= f.button :submit, label: 'Add inspiration', class: "btn btn-blue" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_modal_add_partition.html.erb
<div class="modal fade" id="partitionModal" tabindex="-1" role="dialog" aria-labelledby="partitionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h6 class="modal-title">Add a new Sheet</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for [@track, @partition] do |f| %>
          <%= f.input :name %>
          <%= f.association :instrument, collection: Instrument.all %>
          <%= f.input :resource, as: :file %>

          <div class="text-center mt-4">
            <%= f.button :submit, label: 'Add Sheet', class: "btn btn-blue" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_modal_add_resource.html.erb
<div class="modal fade" id="recordingModal" tabindex="-1" role="dialog" aria-labelledby="recordingModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h6 class="modal-title">Add a new recording</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for [@track, @recording] do |f| %>
          <%= f.input :name %>
          <%= f.input :resource, as: :file %>
          <%= f.input :is_lead, label: 'Lead rhythm track', input_html: { class: "toggle" } %>
          <%= f.association :partition, collection: @track.partitions%>

          <div class="text-center mt-4">
            <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            <%= f.button :submit, label: 'Add Recording', class: "btn btn-blue" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_modal_update_inspiration.html.erb
<div class="modal fade" id="inspirationModalUpdate-<%= inspiration.id %>" tabindex="-1" role="dialog" aria-labelledby="inspirationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h6 class="modal-title">Update your source of inspiration</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for [track, inspiration] do |f| %>
          <%= f.input :name %>
          <div class="text-center mt-4">
            <%= f.button :submit, label: 'Update', class: "btn btn-blue" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_modal_update_partition.html.erb
<div class="modal fade" id="partitionModalUpdate-<%= partition.id %>" tabindex="-1" role="dialog" aria-labelledby="partitionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h6 class="modal-title">Update your Sheet</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for [track, partition] do |f| %>
          <%= f.input :name %>
          <%= f.association :instrument, collection: Instrument.all %>
          <%= f.input :resource, as: :file %>

          <div class="text-center mt-4">
            <%= f.button :submit, label: 'Update', class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_modal_update_ressource.html.erb
<div class="modal fade" id="recordingModalUpdate-<%= recording.id %>" tabindex="-1" role="dialog" aria-labelledby="recordingModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h6 class="modal-title">Update your recording</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for [track, recording] do |f| %>
          <%= f.input :name %>
          <%= f.input :resource, as: :file %>
          <%= f.input :is_lead, label: 'Lead rhythm track', input_html: { class: "toggle", id: "recording-is-lead-#{recording.id}" } %>
          <%= f.association :partition, collection: track.partitions%>

          <div class="text-center mt-4">
            <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            <%= f.button :submit, label: 'Update', class: "btn btn-blue" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% if user_signed_in? %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <h2><span id="logo">(<i class="fas fa-microphone-alt"></i>)</span> My music band</h2>
    <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <h2><span id="logo">(<i class="fas fa-microphone-alt"></i>)</span> My music band</h2>
    <% end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
<!--       <li>
        <div class="lang dropdown">
          <div class="dropdown-toggle" id="langDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
            <% case I18n.locale %>
            <% when :fr %>
              <%= image_tag "Flag_of_France.svg", class: "flag" %>
            <% else %>
              <%= image_tag "Flag_of_the_United_Kingdom.svg", class: "flag" %>
            <% end %>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="langDropdown">
            <%= link_to 'Français', root_path(locale: :fr), class: "dropdown-item" %>
            <%= link_to 'English', root_path(locale: :en), class: "dropdown-item" %>
          </div>
        </div>
      </li> -->
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar.key, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "All my bands", my_bands_path, class: "dropdown-item" %>
            <% current_user.bands.each do |band| %>
            <%= link_to "-#{band.name}", band_path(band), class: "dropdown-item" %>
            <% end %>
            <%= link_to "Create a band", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>