config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :my do
    resources :bands, only:[:index]
  end

  resources :bands, only: [:show, :create] do
    resources :tracks, only:[:create]
  end

  resources :tracks, only:[:index, :show] do
    resources :comments, only:[:create]
    resources :partitions, only:[:create, :show, :destroy, :update]
    resources :recordings, only:[:index, :create, :destroy, :update]
    resources :inspirations, only:[:create, :update, :destroy]
  end

  resources :partitions, only: [:show]
  resources :inspirations, only: [:show]

end

app/models/band.rb
class Band < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :tracks

  has_one_attached :photo

  validates :name, presence: true

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def show
    @band = Band.find(params[:id])
    @track = Track.new
    @member = Member.new
  end

  def create
    @band = Band.new(band_params)
    @band.creation_year = Date.today.year unless @band.creation_year != ""
    member = Member.new(user: current_user, band: @band)

    if @band.save && member.save
      redirect_to band_path(@band)
    else
      @band = Band.new
      render 'my/bands/index'
    end
  end

  private

  def band_params
    params.require(:band).permit(:name, :description, :creation_year, :photo)
  end
end

app/controllers/my/bands_controller.rb
class My::BandsController < ApplicationController
  def index
    @bands = Band.joins(:members).where(members: { user_id: current_user })
    @band = Band.new
  end
end

app/views/bands/_modal_new_band.html.erb
<div class="modal fade" id="newBandModal" tabindex="-1" role="dialog" aria-labelledby="newBandModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h6 class="modal-title">Create a new band!</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for [@band] do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :creation_year %>
          <%= f.input :photo, as: :file %>

          <div class="text-center mt-4">
            <%= f.button :submit, label: 'Assemble!', class: "btn btn-blue" %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/bands/_tracks-list.html.erb
<% @band.tracks.each do |track| %>
  <%= link_to track_path(track) do %>
    <div class="card-track my-3 grow shadow-orange">
      <% if track.photo.attached? %>
        <%= cl_image_tag track.photo.key %>
      <% else %>
        <%= image_tag "track_default.png" %>
      <% end %>
      <div class="card-track-infos flex-grow-1">
        <div class="d-flex justify-content-between">
          <h2><%= track.title %></h2>
          <p class="m-0"><%= track.style %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><%= track.duration / 60 %>m<%= track.duration % 60 %>s</p>
          <p><%= track.tempo %> bpm</p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/bands/_users-list.html.erb
<div class="shadow-orange pt-3 pl-3 pb-1 bg-white">
  <% @band.users.each do |user| %>
    <ul class='list-inline'>
      <li class="list-inline-item"><%= cl_image_tag user.avatar.key, class:"avatar-large" %></li>
      <li class="list-inline-item"><%= user.first_name %></li>
      <li class="list-inline-item">
        <% case user.instrument.name %>
        <% when "Guitar" %>
          <%= image_tag "icon_acoustic_guitar.svg", class: "user-instrument" %>
        <% when "Bass" %>
          <%= image_tag "icon_electric_bass.svg", class: "user-instrument" %>
        <% when "Drums" %>
          <%= image_tag "icon_drums.svg", class: "user-instrument" %>
        <% when "Vocals" %>
          <%= image_tag "icon_microphone.svg", class: "user-instrument" %>
        <% else %>
          <%= image_tag "icon_music.svg", class: "user-instrument" %>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>

app/views/bands/show.html.erb
<div id="particles-js"></div>
<div class="banner-small">
  <div class="banner-slanted"></div>
  <%= image_tag "rocks.png", alt: "Rock on hand sign" ,id: "rocks" %>


  <h1><%= @band.name %></h1>
  <p><%= @band.description %></p>
  <%= render "shared/button_back_to_my_bands"%>
</div>

<div class ="container pb-5 pt-3" style="margin-top:143px">
  <div class="row">

    <div class="col-lg-8 pr-5">
      <ul class="list-inline justify-content-center pb-3">
        <li class="list-inline-item"><h2 class="no-pm-bottom title-40 text-shadow-orange">Tracks Library</h2></li>
        <%= link_to "#newTrackModal", "data-toggle" => "modal" do %>
          <li class="list-inline-item"><button type="button" class="btn btn-plus"><h2><i class="fas fa-plus-circle"></i></h2></button></li>
        <% end %>
      </ul>
      <div class="pl-5">
        <%= render "bands/tracks-list", track: @track %>
      </div>
    </div>

    <div class="col-lg-4">
       <ul class="list-inline pt-5 pb-3">
        <li class="list-inline-item"><h2 class="no-pm-bottom title-40 text-shadow-orange">Crew</h2></li>
        <li class="list-inline-item"><button type="button" class="btn btn-plus"><h2><i class="fas fa-plus-circle"></i></h2></button></li>
      </ul>
      <div class="pl-5">
        <%= render "bands/users-list", user: @user %>
      </div>
    </div>

  </div>

  <!-- particles.js container -->
  <!-- <div id="particles-js"></div> -->
  <!-- <script src="particles.js"></script> -->

</div>

<%= render 'tracks/modal_new_track' %>