config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :my do
    resources :bands, only:[:index]
  end

  resources :bands, only: [:show, :create] do
    resources :tracks, only:[:create]
  end

  resources :tracks, only:[:index, :show] do
    resources :comments, only:[:create]
    resources :partitions, only:[:create, :show, :destroy, :update]
    resources :recordings, only:[:index, :create, :destroy, :update]
    resources :inspirations, only:[:create, :update, :destroy]
  end

  resources :partitions, only: [:show]
  resources :inspirations, only: [:show]

end

app/models/partition.rb
class Partition < ApplicationRecord
  belongs_to :user
  belongs_to :track
  has_many :recordings
  belongs_to :instrument

  has_one_attached :resource

  validates :name, presence: true
  validates :instrument, presence: true
end

app/controllers/partitions_controller.rb
class PartitionsController < ApplicationController
  def show
    @partition = Partition.find(params[:id])
    @recording = Recording.all
    @new_recording = Recording.new
    @track = @partition.track
  end

  def create
    @partition = Partition.new(partition_params)
    @partition.user = current_user
    @track = Track.find(params[:track_id])
    @partition.track = @track

    @recording = Recording.new
    @inspiration = Inspiration.new

    if @partition.save
      redirect_to track_path(@track)
    else
      @comment = Comment.new
      render 'tracks/show'
    end
  end

  def update
    @partition = Partition.find(params[:id])
    @partition.update(partition_params)
    redirect_to track_path(params[:track_id])
  end

  def destroy
    @partition = Partition.find(params[:id])
    @partition.destroy
    redirect_to track_path(params[:track_id])
  end

  private

  def partition_params
    params.require(:partition).permit(:name, :instrument_id, :resource)
  end
end

app/views/partitions/_index.html.erb
<div class="container rounded py-3">
  <div class="d-flex align-items-center">
    <h3 class="title-32 text-shadow-orange">Sheets and Tabs</h3>
    <%= link_to "#partitionModal", class: "btn btn-plus ml-3", "data-toggle" => "modal" do %>
      <h3><i class="fas fa-plus-circle"></i></h3>
    <% end %>
  </div>

  <% @track.partitions.each do |partition| %>
    <div class="resource-card grow-resource">

      <%= link_to partition_path(partition) do %>
        <div class="d-flex align-items-center">
          <% case partition.instrument.name %>
          <% when "Guitar" %>
            <%= image_tag "icon_acoustic_guitar.svg", class: "resource-card-icon" %>
          <% when "Bass" %>
            <%= image_tag "icon_electric_bass.svg", class: "resource-card-icon" %>
          <% when "Drums" %>
            <%= image_tag "icon_drums.svg", class: "resource-card-icon" %>
          <% when "Vocals" %>
            <%= image_tag "icon_microphone.svg", class: "resource-card-icon" %>
          <% else %>
            <%= image_tag "icon_music.svg", class: "resource-card-icon" %>
          <% end %>

          <p>
            <%= partition.name %>
          </p>
        </div>
      <% end %>

      <div class="d-flex ml-auto align-items-center">
        <div class="icon-display-hover">
          <%= link_to "#partitionModalUpdate-#{partition.id}", "data-toggle" => "modal" do %>
          <i class="fas fa-pencil-alt mr-2"></i>
          <% end %>
          <%= link_to track_partition_path(@track, partition), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="far fa-trash-alt mr-3"></i>
          <% end %>
        </div>
      </div>
      <div>
      <%= link_to "Start recording", partition_path(partition), class: "btn btn-partition d-flex align-items-center"  %>
      </div>

    </div>
  <% end %>
</div>

app/views/partitions/show.html.erb
<div class="partition-show">
  <div class="banner-small banner-transparent text-center">
    <%= link_to  track_path(@track), class: "btn btn-back" do %>
      <i class="fas fa-fast-backward"></i>
    <% end %>

      <h1 class="text-shadow-orange"><%= @partition.track.title %></h1>

      <%= image_tag "plug.png", alt: "Recording cable" ,id: "plug" %>
  </div>
  <div class="counter">
    <div class="nums">
      <span class="double">1</span>
      <span class="double">2</span>
      <span>1</span>
      <span>2</span>
      <span>3</span>
      <span>4</span>
    </div>
  </div>
  <div class="container container-partition">
    <div class="text-center">
      <% if @partition.resource.attached? %>
      <%= cl_image_tag @partition.resource.key, width: 800 %>
      <% end %>
    </div>
  </div>
  <div class= "card-player fixed-bottom d-flex flex-column">
    <div class="card-record mt-4 d-flex flex-column">
      <div class="d-flex flex-row justify-content-center" style="height:60px">
        <button class="btn-record btn-main"><i class="fas fa-record-vinyl"></i></button>
        <button class="btn-stop btn-main button-inactive"><i class="far fa-stop-circle"></i></button>
        <div class="main-controls" data-trackid="<%= @partition.track.id %>" data-partitionid="<%= @partition.id %>" data-userid="<%= current_user.id %>">
            <canvas class="visualizer" height="37px"></canvas>
    <!--         <div id="buttons">
              <button class="record"><i class="fas fa-record-vinyl"></i></button>
              <button class="stop"><i class="fas fa-stop"></i></button>
            </div> -->
        </div>
      </div>
      <div class="card-player-listen d-flex justify-content-center">
        <div class="sound-clips d-flex flex-row">

          <%= simple_form_for [@track, @new_recording] do |f| %>
            <%= f.hidden_field :name, input_html: { :id => "name-field" } %>
            <%= f.hidden_field :resource, as: :file, input_html: { :id => "resource-field" } %>
            <%= f.hidden_field :is_lead, label: 'Lead rhythm track' %>
            <%= f.hidden_field :partition, label_method: :name, value_method: :id, include_blank: false, input_html: { :id => "partition-field" } %>

            <div class="text-center">
              <%= f.button :submit, 'Save', class: "btn-save d-none" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div>
      <a class="dropdown-recordings" data-toggle="collapse" data-target="#collapseRecordings" aria-expanded="false" aria-controls="collapseExample">
    Select your recordings buddy <i class="fas fa-angle-down icon-dropdown"></i>
      </a>
      <div class="collapse" id="collapseRecordings">
        <div class="list-recordings">
          <ul class="list-unstyled">
            <li class="text-center"><button class="btn-checkbox btn-checkbox-play"><i class="fas fa-play"></i></button></li>
            <li class="text-center"><button class="btn-checkbox btn-checkbox-pause button-inactive"><i class="fas fa-pause"></i></button></li>
            <% @track.recordings.each do |record| %>
              <li class="text-center">
                <input class="toggle audio checkrecording" type="checkbox" data-recordurl="<%= cloudinary_url(record.resource.key, resource_type: :video) %>" name="recording" id=<%= "recording-#{record.id}" %> >
                </input>
                <label class="d-inline" for=<%= "recording-#{record.id}" %> >
                  <%= record.name %>
                </label>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>